In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
datos = pd.read_csv('cr.csv')

In [4]:
datos.head()

EMPLEO  INGRESOS  CREDITO
0    True      3000     True
1    True      1000    False
2   False         0    False
3    True      1500     True
4    True      2000     True

In [5]:
target = 'CREDITO'
datos[target].unique()

array([ True, False])

In [6]:
# Separar las características en x & y siendo y nuestro objetivo
# X es igual a todo el data set pero sin target
X = datos.drop(target, axis=1)

In [7]:
# Cargamos nuestro objetivo
Y = datos[target]

In [8]:
# Separamos datos de prueba y de entrenamiento
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.3)

In [9]:
arbol = DecisionTreeClassifier()

In [10]:
arbol.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [11]:
predicciones = arbol.predict(x_test)

In [12]:
predicciones

array([False, False, False, False,  True, False, False, False, False,
       False,  True, False, False, False,  True,  True, False, False,
       False, False, False,  True, False, False,  True, False,  True,
        True,  True,  True, False, False,  True,  True])

In [13]:
x_test

EMPLEO  INGRESOS
77    False      2713
45    False      2746
51    False      4645
56    False      1128
21     True      4661
107   False      1881
109   False      1004
33    False      1309
39    False      3427
7      True      1360
94     True      3461
6      True       750
100    True       858
26    False      3410
24     True      2615
111    True      2492
50    False      4758
44    False      1737
14    False      2353
47    False      1097
38    False      2256
71     True      1886
75    False      3035
19    False      2297
30     True      2175
35    False       750
99     True      4198
63     True      3711
46     True      3007
91     True      4281
97    False      2343
98    False      3446
0      True      3000
96     True      4176

In [14]:
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00        22
        True       1.00      1.00      1.00        12

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34



In [15]:
print(confusion_matrix(y_test,predicciones))

[[22  0]
 [ 0 12]]


In [16]:
temp = x_test
a = temp.to_numpy()

In [17]:
print(a)

[[False 2713]
 [False 2746]
 [False 4645]
 [False 1128]
 [True 4661]
 [False 1881]
 [False 1004]
 [False 1309]
 [False 3427]
 [True 1360]
 [True 3461]
 [True 750]
 [True 858]
 [False 3410]
 [True 2615]
 [True 2492]
 [False 4758]
 [False 1737]
 [False 2353]
 [False 1097]
 [False 2256]
 [True 1886]
 [False 3035]
 [False 2297]
 [True 2175]
 [False 750]
 [True 4198]
 [True 3711]
 [True 3007]
 [True 4281]
 [False 2343]
 [False 3446]
 [True 3000]
 [True 4176]]


In [27]:
print("Empleo \tSalario \tCrédito")
for x in range(len(predicciones)):
    print("{} \t{} \t\t{}".format(a[x][0],a[x][1],predicciones[x]))

Empleo 	Salario 	Crédito
False 	2713 		False
False 	2746 		False
False 	4645 		False
False 	1128 		False
True 	4661 		True
False 	1881 		False
False 	1004 		False
False 	1309 		False
False 	3427 		False
True 	1360 		False
True 	3461 		True
True 	750 		False
True 	858 		False
False 	3410 		False
True 	2615 		True
True 	2492 		True
False 	4758 		False
False 	1737 		False
False 	2353 		False
False 	1097 		False
False 	2256 		False
True 	1886 		True
False 	3035 		False
False 	2297 		False
True 	2175 		True
False 	750 		False
True 	4198 		True
True 	3711 		True
True 	3007 		True
True 	4281 		True
False 	2343 		False
False 	3446 		False
True 	3000 		True
True 	4176 		True
