In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
datos = pd.read_csv('cr.csv')

In [4]:
datos.head()

EMPLEO  INGRESOS  CREDITO
0    True      3000     True
1    True      1000    False
2   False         0    False
3    True      1500     True
4    True      2000     True

In [5]:
target = 'CREDITO'
datos[target].unique()

array([ True, False])

In [6]:
# Separar las características en x & y siendo y nuestro objetivo
# X es igual a todo el data set pero sin target
X = datos.drop(target, axis=1)

In [7]:
# Cargamos nuestro objetivo
Y = datos[target]

In [8]:
# Separamos datos de prueba y de entrenamiento
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.3)

In [9]:
arbol = DecisionTreeClassifier()

In [10]:
arbol.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [11]:
predicciones = arbol.predict(x_test)

In [12]:
predicciones

array([False, False, False,  True, False,  True, False, False,  True,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False,  True,  True, False, False, False])

In [13]:
x_test

EMPLEO  INGRESOS
64    False      4163
54     True      1150
12    False      3185
55     True      3587
31     True      1321
52     True      4762
110   False      3626
81    False      2709
32     True      3799
86     True      4622
65    False       763
25    False      1999
44    False      1737
56    False      1128
5     False      1700
9     False      1748
26    False      3410
71     True      1886
40     True       785
68     True      1056
45    False      2746
16     True       865
100    True       858
80    False      2325
103    True      3691
106    True      1705
2     False         0
101   False      2158
78    False      1012
90     True      2399
63     True      3711
22    False      2591
14    False      2353
19    False      2297

In [14]:
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00        25
        True       1.00      1.00      1.00         9

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34



In [15]:
print(confusion_matrix(y_test,predicciones))

[[25  0]
 [ 0  9]]


In [16]:
type(x_test)

pandas.core.frame.DataFrame