In [14]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
datos = pd.read_csv('cr.csv')
datos.head()

EMPLEO  INGRESOS  CREDITO
0    True      3000     True
1    True      1000    False
2   False         0    False
3    True      1500     True
4    True      2000     True

In [16]:
target = 'CREDITO'
datos[target].unique()

array([ True, False])

In [17]:
# Separar las características en x & y siendo y nuestro objetivo
# X es igual a todo el data set pero sin target
X = datos.drop(target, axis=1)

# Cargamos nuestro objetivo
Y = datos[target]

In [18]:
# Separamos datos de prueba y de entrenamiento
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.3)

In [19]:
arbol = DecisionTreeClassifier()
arbol.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [20]:
predicciones = arbol.predict(x_test)
predicciones

array([ True, False,  True, False, False, False, False,  True,  True,
       False, False, False, False, False, False,  True, False,  True,
       False, False, False, False, False,  True,  True,  True, False,
        True, False, False, False, False, False, False])

In [21]:
x_test

EMPLEO  INGRESOS
63     True      3711
87    False      4586
95     True      1602
35    False       750
79     True      1295
75    False      3035
19    False      2297
90     True      2399
32     True      3799
81    False      2709
38    False      2256
2     False         0
93    False      1154
54     True      1150
88    False      4138
55     True      3587
17    False      2575
27     True      2193
67    False      2889
109   False      1004
110   False      3626
31     True      1321
80    False      2325
102    True      1646
41     True      4545
99     True      4198
56    False      1128
103    True      3691
18    False      4212
40     True       785
39    False      3427
29    False       794
73     True      1368
47    False      1097

In [22]:
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00        24
        True       1.00      1.00      1.00        10

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34



In [23]:
print(confusion_matrix(y_test,predicciones))

[[24  0]
 [ 0 10]]


In [24]:
temp = x_test
a = temp.to_numpy()

In [25]:
print("Empleo \tSalario \tCrédito")
for x in range(len(predicciones)):
    print("{} \t{} \t\t{}".format(a[x][0],a[x][1],predicciones[x]))

Empleo 	Salario 	Crédito
True 	3711 		True
False 	4586 		False
True 	1602 		True
False 	750 		False
True 	1295 		False
False 	3035 		False
False 	2297 		False
True 	2399 		True
True 	3799 		True
False 	2709 		False
False 	2256 		False
False 	0 		False
False 	1154 		False
True 	1150 		False
False 	4138 		False
True 	3587 		True
False 	2575 		False
True 	2193 		True
False 	2889 		False
False 	1004 		False
False 	3626 		False
True 	1321 		False
False 	2325 		False
True 	1646 		True
True 	4545 		True
True 	4198 		True
False 	1128 		False
True 	3691 		True
False 	4212 		False
True 	785 		False
False 	3427 		False
False 	794 		False
True 	1368 		False
False 	1097 		False
